source:
  - type: local
    sourceAbsolutePath: /Users/andreyyurevich/PycharmProjects/xxhash-files-comparation/source
    destinationAbsolutePath: /Users/andreyyurevich/PycharmProjects/xxhash-files-comparation/dest